// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcuxvvpagdiaslaeofdb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjdXh2dnBhZ2RpYXNsYWVvZmRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMjE4MDMsImV4cCI6MjA2OTc5NzgwM30.zd93PYN-5FBm6LswykCyF8Byhml1-LvDprpd2Gn3eMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});